services:
  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=production

  nextjs-app:
    build:
      context: ./nextjs
      dockerfile: Dockerfile.prod
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./nextjs/.env