services:
  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production

  nextjs-app:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "6500:6500"
    environment:
      - NODE_ENV=production