version: '3.8'

services:
  nextjs:
    build:
      context: ./nextjs/nextjs_proc
    container_name: kiosken-test
    ports:
      - "6000:3000"
    env_file:
      - .env
    restart: unless-stopped

  websocket-server:
    build:
      context: ./server
    container_name: kiosk_ws-test
    ports:
      - "8001:8001"
    restart: unless-stopped
