version: '3.8'

services:
  nextjs:
    build:
      context: ./nextjs
    container_name: kiosken-test
    ports:
      - "6500:3000"
    env_file:
      - .env
    restart: unless-stopped

  websocket-server:
    build:
      context: ./server
    container_name: kiosken_ws
    ports:
      - "8001:8001"
    restart: unless-stopped
