export type Purchase = {
  purchaseUuid: string;
  source: string;
  userUuid: string;
  currency: string;
  country: string;
  amount: number;
  vatAmount: number;
  timestamp: number;
  created: string;
  gpsCoordinates: GpsCoordinates;
  purchaseNumber: number;
  userDisplayName: string;
  udid: string;
  organizationUuid: string;
  products: Product[];
  discounts: any[];
  payments: Payment[];
  references: References;
  taxationMode: string;
  taxationType: string;
};

export type GpsCoordinates = {
  longitude: number;
  latitude: number;
  accuracyMeters: number;
};

export type Product = {
  id: string;
  productUuid: string;
  variantUuid: string;
  name: string;
  variantName: string;
  sku: string;
  unitPrice: number;
  quantity: number;
  vatPercentage: number;
  taxRates: TaxRate[];
  taxExempt: boolean;
  fromLocationUuid: string;
  toLocationUuid: string;
  autoGenerated: boolean;
  type: string;
  details: any;
};

export type TaxRate = {
  percentage: number;
};

export type Payment = {
  uuid: string;
  amount: number;
  type: string;
  attributes: PaymentAttributes;
};

export type PaymentAttributes = {
  changeAmount: number;
  handedAmount: number;
};

export type References = {
  checkoutUUID: string;
};

export type PurchaseEvent = {
  organizationUuid: string;
  messageUuid: string;
  eventName: string;
  messageId: string;
  payload: Purchase;
  timestamp: string;
};
