name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: deployment_lock
      cancel-in-progress: false
    env:
      PROJECT_PATH: /var/www/kiosk_project_dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          set +x
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          set +x
          echo 'ZETTLE_CLIENT_SECRET=${{ secrets.ZETTLE_CLIENT_SECRET }}' > .env
          echo 'ZETTLE_CLIENT_ID=${{ secrets.ZETTLE_CLIENT_ID }}' >> .env

      - name: Copy .env to OpenStack server
        run: |
          scp -v -i ~/.ssh/key .env ${{ secrets.USER }}@${{ secrets.HOST }}:${{ env.PROJECT_PATH }}/.env.temp
          ssh -v -i ~/.ssh/key ${{ secrets.USER }}@${{ secrets.HOST }} << 'ENDSSH'
          set -e
          cd ${{ env.PROJECT_PATH }}
          cat .env.temp >> .env
          rm .env.temp
          ENDSSH

      - name: Deploy frontend + WebSocket server
        run: |
          ssh -v -i ~/.ssh/key ${{ secrets.USER }}@${{ secrets.HOST }} << 'ENDSSH'
          set -e
          cd ${{ env.PROJECT_PATH }}
          chmod 0600 .env
          git pull -f
          which pnpm || curl -fsSL https://get.pnpm.io/install.sh | sh -
          make dev
          ENDSSH