name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: deployment_lock
      cancel-in-progress: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          echo 'ZETTLE_CLIENT_SECRET=${{ secrets.ZETTLE_CLIENT_SECRET }}' > ./nextjs/.env.prod
          echo 'ZETTLE_CLIENT_ID=${{ secrets.ZETTLE_CLIENT_ID }}' >> ./nextjs/.env.prod
          echo 'NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL_PROD }}' >> ./nextjs/.env.prod
          echo 'PUBLIC_PORT=${{ secrets.PUBLIC_PORT_PROD }}' >> ./nextjs/.env.prod

          # Create .env.dev for server
          echo 'PUBLIC_PORT=${{ secrets.PUBLIC_PORT_PROD }}' > ./server/.env.prod

      - name: Copy .env to OpenStack server
        run: |
          scp -v -i ~/.ssh/key ./nextjs/.env.prod ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/kiosk_project/nextjs/.env

          scp -v -i ~/.ssh/key ./server/.env.prod ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/kiosk_project/server/.env

      - name: Deploy to OpenStack server
        run: |
          ssh -v -i ~/.ssh/key ${{ secrets.USER }}@${{ secrets.HOST }} << 'ENDSSH'
          cd /var/www/kiosk_project
          chmod 0600 nextjs/.env server/.env
          git pull -f
          make prod
          ENDSSH
